# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bossstyling.com
title: Boss Styling
subTitle: Virtual Stylist
email: bossstyling@hotmail.com
author: Boss Styling
description: Virtual Stylist inspired by the Boss women of the world.
copyright: 'Copyright &copy; 2019 Boss Styling. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
baseurl:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty


# ------------------------------------------------ #
# ------------------------------------------------ #
#   The Following Configures The Website Content   #
# ------------------------------------------------ #
# ------------------------------------------------ #


# --------------------------------------------- #
#   Configure Social Media Links On Home Page   #
# --------------------------------------------- #

social:
  - title: instagram
    url: https://instagram.com/bossstyling
  - title: facebook
    url: https://www.facebook.com/Boss-Styling-2169009916487232/



# ------------------------------------------ #
#   Write New Instagram Posts On Home Page   #
# ------------------------------------------ #

instagramPosts:
  - linkUrl: https://www.instagram.com/p/BxU_273BUOO/
    imgUrl: img/latest_insta_posts/BOSS_PINK_SUIT_TRAINER_GREYTOP_STYLING.jpg
    subTitle: ğŸ”¥ ğ“’ğ“ªğ“µğ“µ ğ“²ğ“½ ğ“¼ğ“¶ğ“ªğ“¼ğ“¾ğ“ªğ“µ ğŸ”¥
  - linkUrl: https://www.instagram.com/p/BxrU5nlBTYh/
    imgUrl: img/latest_insta_posts/BOSS_denim_blazer_dress_.jpg
    subTitle: ğŸ”¥ ğ•¸ğ–”ğ–“ğ–‰ğ–†ğ– ğ–’ğ–”ğ–™ğ–ğ–›ğ–†ğ–™ğ–”ğ–— ğŸ‘
  - linkUrl: https://www.instagram.com/p/BzI7ZeegsTL/
    imgUrl: img/latest_insta_posts/slave4ubossstyling.jpg
    subTitle: ğŸ”¥ ğ•Šğ•ƒğ”¸ğ•ğ”¼ ğŸœ â„•ğ•†ğ”¹ğ•†ğ”»ğ• ğŸ”¥



# ------------------------------------- #
#   Write New Blog Posts On Blog Page   #
# ------------------------------------- #

blogPosts:
  - title: Smasual Womenswear Is On Trend
    description: Looking for a "smasual" outfit? Today we discuss how to obtain that required look for your everyday outings.
    paragraphOne: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    paragraphTwo: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    imgUrlOne: https://www.essence.com/wp-content/uploads/2019/09/marquee_header_superwide_3x1_who.jpg
    imgUrlTwo: /img/latest_insta_posts/BOSS_PINK_SUIT_TRAINER_GREYTOP_STYLING.jpg
    imgUrlOneLink:
    imgUrlTwoLink:
    imgUrlTwoSubtitle: I am subtitle 2
    publicationDate: 10/12/2019
  - title: I am blog title 2
    description: I am description 2
    paragraphOne: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    paragraphTwo: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    imgUrlOne: https://www.essence.com/wp-content/uploads/2019/08/ICL-1920x640.jpg
    imgUrlTwo: /img/latest_insta_posts/BOSS_PINK_SUIT_TRAINER_GREYTOP_STYLING.jpg
    imgUrlOneLink:
    imgUrlTwoLink:
    imgUrlTwoSubtitle: I am subtitle 2
    publicationDate: 11/12/2019