# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bossstyling.com
title: Boss Styling
subTitle: Virtual Stylist
email: bossstyling@hotmail.com
author: Boss Styling
description: Virtual Stylist inspired by the Boss women of the world.
copyright: 'Copyright &copy; 2019 Boss Styling. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
baseurl:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram.com/bossstyling
  - title: facebook
    url: https://www.facebook.com/Boss-Styling-2169009916487232/

instagramPosts:
  - linkUrl: https://www.instagram.com/p/BxU_273BUOO/
    imgUrl: img/latest_insta_posts/BOSS_PINK_SUIT_TRAINER_GREYTOP_STYLING.jpg
    subTitle: ğŸ”¥ ğ“’ğ“ªğ“µğ“µ ğ“²ğ“½ ğ“¼ğ“¶ğ“ªğ“¼ğ“¾ğ“ªğ“µ ğŸ”¥
  - linkUrl: https://www.instagram.com/p/BxrU5nlBTYh/
    imgUrl: img/latest_insta_posts/BOSS_denim_blazer_dress_.jpg
    subTitle: ğŸ”¥ ğ•¸ğ–”ğ–“ğ–‰ğ–†ğ– ğ–’ğ–”ğ–™ğ–ğ–›ğ–†ğ–™ğ–”ğ–— ğŸ‘
  - linkUrl: https://www.instagram.com/p/BzI7ZeegsTL/
    imgUrl: img/latest_insta_posts/slave4ubossstyling.jpg
    subTitle: ğŸ”¥ ğ•Šğ•ƒğ”¸ğ•ğ”¼ ğŸœ â„•ğ•†ğ”¹ğ•†ğ”»ğ• ğŸ”¥

blogPosts:
  - title: I am blog post number 1
    description: descripion 1
    publicationDate: 11/12/2019
  - title: I am blog post number 2
    description: descripion 2
    publicationDate: 12/12/2019